-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 16:46:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ConsultorioSaludDH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ConsultorioSaludDH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ConsultorioSaludDH` DEFAULT CHARACTER SET utf8 ;
USE `ConsultorioSaludDH` ;

-- -----------------------------------------------------
-- Table `ConsultorioSaludDH`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsultorioSaludDH`.`Paciente` (
  `id` INT NOT NULL,
  `identificacion_salud` BIGINT NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsultorioSaludDH`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsultorioSaludDH`.`Especialidad` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsultorioSaludDH`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsultorioSaludDH`.`Medico` (
  `id` INT NOT NULL,
  `matricula` BIGINT NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `Especialidad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Especialidad_id`),
  INDEX `fk_Medico_Especialidad_idx` (`Especialidad_id` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Especialidad`
    FOREIGN KEY (`Especialidad_id`)
    REFERENCES `ConsultorioSaludDH`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsultorioSaludDH`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsultorioSaludDH`.`Turno` (
  `Paciente_id` INT NOT NULL,
  `Medico_id` INT NOT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`Paciente_id`, `Medico_id`),
  INDEX `fk_Turno_Medico1_idx` (`Medico_id` ASC) VISIBLE,
  CONSTRAINT `fk_Turno_Paciente1`
    FOREIGN KEY (`Paciente_id`)
    REFERENCES `ConsultorioSaludDH`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Medico1`
    FOREIGN KEY (`Medico_id`)
    REFERENCES `ConsultorioSaludDH`.`Medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
