-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 14:58:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UniversoLector
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UniversoLector
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniversoLector` DEFAULT CHARACTER SET utf8 ;
USE `UniversoLector` ;

-- -----------------------------------------------------
-- Table `UniversoLector`.`Socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Socio` (
  `Codigo` INT NOT NULL,
  `DNI` INT NULL,
  `Apellidos` VARCHAR(100) NULL,
  `Nombre` VARCHAR(100) NULL,
  `Direccion` VARCHAR(200) NULL,
  `Localidad` VARCHAR(100) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLector`.`TelefonoxSocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`TelefonoxSocio` (
  `Codigo` INT NOT NULL,
  `NroTelefono` VARCHAR(100) NULL,
  `Socio_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`, `Socio_Codigo`),
  INDEX `fk_TelefonoxSocio_Socio_idx` (`Socio_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_TelefonoxSocio_Socio`
    FOREIGN KEY (`Socio_Codigo`)
    REFERENCES `UniversoLector`.`Socio` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Autor` (
  `Codigo` INT NOT NULL,
  `Apellido` VARCHAR(100) NULL,
  `Nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Editorial` (
  `Codigo` INT NOT NULL,
  `Razon_Social` VARCHAR(100) NULL,
  `Telefono` VARCHAR(100) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Libro` (
  `Codigo` INT NOT NULL,
  `ISBN` VARCHAR(130) NULL,
  `Titulo` VARCHAR(200) NULL,
  `Anio_Escritura` DATE NULL,
  `Anio_Edicion` DATE NULL,
  `Autor_Codigo` INT NOT NULL,
  `Editorial_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`, `Autor_Codigo`, `Editorial_Codigo`),
  INDEX `fk_Libro_Autor1_idx` (`Autor_Codigo` ASC) VISIBLE,
  INDEX `fk_Libro_Editorial1_idx` (`Editorial_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_Autor1`
    FOREIGN KEY (`Autor_Codigo`)
    REFERENCES `UniversoLector`.`Autor` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Editorial1`
    FOREIGN KEY (`Editorial_Codigo`)
    REFERENCES `UniversoLector`.`Editorial` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `UniversoLector`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Prestamo` (
  `Codigo` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `Fecha_Devolucion` DATE NULL,
  `Fecha_Tope` DATE NULL,
  `Socio_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`, `Socio_Codigo`),
  INDEX `fk_Prestamo_Socio1_idx` (`Socio_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Socio1`
    FOREIGN KEY (`Socio_Codigo`)
    REFERENCES `UniversoLector`.`Socio` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Volumen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Volumen` (
  `Codigo` INT NOT NULL,
  `Deteriorado` TINYINT(1) NULL,
  `Libro_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`, `Libro_Codigo`),
  INDEX `fk_Volumen_Libro1_idx` (`Libro_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Volumen_Libro1`
    FOREIGN KEY (`Libro_Codigo`)
    REFERENCES `UniversoLector`.`Libro` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLector`.`PrestamoxVolumen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`PrestamoxVolumen` (
  `Codigo` INT NOT NULL,
  `Volumen_Codigo` INT NOT NULL,
  `Prestamo_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`, `Volumen_Codigo`, `Prestamo_Codigo`),
  INDEX `fk_PrestamoxVolumen_Volumen1_idx` (`Volumen_Codigo` ASC) VISIBLE,
  INDEX `fk_PrestamoxVolumen_Prestamo1_idx` (`Prestamo_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_PrestamoxVolumen_Volumen1`
    FOREIGN KEY (`Volumen_Codigo`)
    REFERENCES `UniversoLector`.`Volumen` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrestamoxVolumen_Prestamo1`
    FOREIGN KEY (`Prestamo_Codigo`)
    REFERENCES `UniversoLector`.`Prestamo` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
